### PR TITLE
by Himanshu

### PR DESCRIPTION
**Pull request by Himanshu-fullstack**
menu updated

### CODE REVIEW

**Comment by Himanshu-fullstack** [comment]
Bhai ye menu ok kar do

**Comment by Himanshu-fullstack** [comment]
Kindly approve

**Comment by Himanshu-fullstack** [comment]
hello adsad

**Comment by Vinaashuk** [comment]
Theek hai bhai kar diya update

**Comment by Vinaashuk** [comment]
Finally merged

**Pull request merged**
